version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dishes
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
        - meals

  meals_api:
    build:
        context: .
        dockerfile: Dockerfile
    image: meals_api:v1
    depends_on:
      db:
        condition: service_healthy
    networks:
        - meals
    ports:
        - "8000:8000"

networks:
    meals:
        driver: bridge